name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      # Step 3: Install backend dependencies (root)
    #   - name: Install backend dependencies
    #     run: npm install --force
    #     working-directory: .

      # # Step 4: Install frontend dependencies
      # - name: Install frontend dependencies
      #   run: npm install --force
      #   working-directory: ./frontend

      # # Step 5: Build the frontend application
      # - name: Build frontend application
      #   run: npm run build
      #   working-directory: ./frontend

      # Step 6: Setup SSH for Deployment
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H dev.zealits.com >> ~/.ssh/known_hosts

      # Step 7: Deploy to the server
      - name: Deploy to server
        if: github.ref == 'refs/heads/main'
        run: |
          ssh admin@dev.zealits.com << 'EOF'
           echo "ðŸ” Starting deployment to remote server"

           if [ -f ~/medicalTourism/backend/.env ]; then
             echo "ðŸ“ Backing up existing .env file"
             cp ~/medicalTourism/backend/.env ~/.env.bak
           fi

           if [ -d ~/medicalTourism ]; then
             echo "ðŸ“‚ Pulling latest changes from Git"
             cd ~/medicalTourism
             git reset --hard
             git pull origin main
           else
             echo "ðŸ“‚ Cloning repository"
             git clone https://github.com/zealits/medicalTourism.git ~/medicalTourism 
             cd ~/medicalTourism 
           fi

           if [ -f ~/.env.bak ]; then
             echo "â™»ï¸ Restoring .env from backup"
             mv ~/.env.bak ~/medicalTourism/backend/.env
           fi

           echo "ðŸ“¦ Installing backend dependencies"
           cd backend
           npm install

           cd ../frontend
           echo "ðŸ“¦ Installing frontend dependencies"
           npm install --force
           echo "ðŸ› ï¸ Building frontend"
           npm run build

           cd ../backend
           echo "ðŸš€ Starting or restarting PM2 process"
           if pm2 list | grep -q "medicaltourism"; then
             echo "ðŸ” Restarting medicaltourism"
             pm2 restart medicaltourism
           else
             echo "â–¶ï¸ Starting medicaltourism"
             pm2 start npm --name "medicaltourism" -- run dev
           fi

           echo "ðŸ“‹ PM2 process list:"
           pm2 list
          EOF